apiVersion: v1
kind: Service
metadata:
  name: jigsaw-puzzle-solver
  labels:
    app: jigsaw-puzzle-solver
spec:
  type: ClusterIP
  selector:
    app: jigsaw-puzzle-solver
  ports:
    - name: http
      port: 3000
      targetPort: 3000
