FROM python:3.8

WORKDIR /app

RUN pip install pyinstaller

COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY python/ .

CMD ["pyinstaller", "--onefile", "executable.py"]
