apiVersion: apps/v1
kind: Deployment
metadata:
  name: jigsaw-puzzle-solver
  namespace: apps
  labels:
    app: jigsaw-puzzle-solver-dev
spec:
  selector:
    matchLabels:
      app: jigsaw-puzzle-solver-dev
  template:
    metadata:
      labels:
        app: jigsaw-puzzle-solver-dev
    spec:
      containers:
        - name: jigsaw-puzzle-solver
          envFrom:
            - secretRef:
                name: jigsaw-puzzle-solver-secrets-dev
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
