apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
nameSuffix: -dev
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: jigsaw-puzzle-solver
  - path: service-patch.yaml
    target:
      kind: Service
      name: jigsaw-puzzle-solver
images:
  - name: jigsaw-puzzle-solver
    newName: registry.kkserver.net/jigsaw-puzzle-solver
    newTag: replace-me
